---
title: "HeVa analysis with all studysets"
author: "Leo Dahl"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
```

# Description

> HeVa analysis between serostatuses within studysets, using all studysets.

# Packages and data

```{r packages, message=F, warning=F}

rm(list = ls())

library(tidyverse)
library(car) # For the leveneTest function
library(DT)

```

Load data

```{r load data}

source("load_cov_npx.R")

cov_npx <- load_cov_npx("abspqn_adj")

source("sep_datasets.R")
out_dir <- "../results/heva/"
```

Loaded data set **`r cov_npx$data_set`**  
from **`r cov_npx$data_path`**, with the following treatment:  
`r cov_npx$norm`


```{r}

npx <- cov_npx$npx
sinfo <- cov_npx$sinfo
binder <- cov_npx$binder

# Turn into character to not get unexpected behaviour from factor
sinfo$grp <- as.character(sinfo$grp)

# Merge duplicates/triplicates
sep_dat <- sep_datasets(npx, sinfo)
npx_umap <- sep_dat$npx_umap
npx_spk <- sep_dat$npx_spk
sinfo_umap <- sep_dat$sinfo_umap %>% mutate(serostatus = case_when(serostatus == "no reactivity" ~ "Seronegative, IgM-IgG-",
                                                                   serostatus == "IgG + IgM" ~ "Seropositive, IgM+IgG+"))
sinfo_spk <- sep_dat$sinfo_spk %>% mutate(serostatus = case_when(serostatus == "IgM" ~ "Early phase, IgM+IgG-",
                                                                 serostatus == "IgG" ~ "Late phase, IgM-IgG+"))
rm(sep_dat)

```

Also get studyset 3

```{r}

ds3 <- load_cov_npx(paste0("ds3_", cov_npx$data_set)) %>% merge_repl()

sinfo_ds3 <- ds3$sinfo %>% rename(serostatus = grp) %>%
  mutate(serostatus = case_when(serostatus == "Negative" ~ "Seronegative, IgG-",
                                serostatus == "Positive" ~ "Seropositive, IgG+"))
npx_ds3 <- ds3$npx %>% filter(sample_id %in% sinfo_ds3$sample_id)
binder_ds3 <- ds3$binfo

```

Loaded data set from **`r ds3$data_path`**

Finally, put all studysets into one list

```{r}
dat <- list("Studyset1" = list("npx" = npx_umap,
                              "sinfo" = sinfo_umap,
                              "name" = "Studyset1"),
            "Studyset2" = list("npx" = npx_spk,
                              "sinfo" = sinfo_spk,
                              "name" = "Studyset2"),
            "Studyset3" = list("npx" = ds3$npx %>% column_to_rownames("sample_id") %>% as.matrix(),
                              "sinfo" = ds3$sinfo %>% filter(sample_id %in% ds3$npx$sample_id) %>% rename(serostatus = grp),
                              "name" = "Studyset3"))
# Make a long format data
dat <- lapply(dat, function(d) {
  npx_long <- d$npx %>% as.data.frame() %>% rownames_to_column("sample_id") %>%
    pivot_longer(cols = -sample_id, names_to = "assay", values_to = "npx") %>%
    left_join(d$sinfo %>% select(sample_id, serostatus), by = "sample_id") %>%
    filter(!is.na(serostatus)) %>%
    mutate(studyset = d$name)
}) %>%
  data.table::rbindlist() %>%
  mutate(serostatus = as.factor(serostatus))
```


# The analysis

```{r}
# Perform analysis per studyset and protein
heva <- dat %>%
  group_by(studyset, assay) %>% nest() %>%
  # Get variance of different serostatuses
  mutate(var1 = map(data, ~ {
    .x %>% filter(str_detect(serostatus, regex("negative|early", ignore_case = T))) %>% pull(npx) %>% var(na.rm = T)
  })) %>%
  mutate(var2 = map(data, ~ {
    .x %>% filter(str_detect(serostatus, regex("positive|late", ignore_case = T))) %>% pull(npx) %>% var(na.rm = T)
  })) %>%
  # Levene test
  mutate(pvalue = map(data, ~ {
    leveneTest(npx ~ serostatus, data = .x)$`Pr(>F)`[1]
  })) %>%
  select(-data) %>%
  unnest(c(var1, var2, pvalue)) %>%
  # FDR per studyset
  ungroup(assay) %>%
  mutate(fdr = p.adjust(pvalue, method = "fdr")) %>%
  ungroup()
```

## Results table

```{r}
datatable(heva, caption = "var1: Variance for seronegative or early group. var2: Variance for seropositive or late group") %>%
  formatSignif(columns = 3:6, digits = 3)
```

```{r}
# Save a table of the results
tbl_out <- heva %>%
  rename(unique_id = assay) %>%
  left_join(binder %>% select(assay, unique_id, gene_name, uniprot_ID), by = "unique_id") %>%
  select(-unique_id) %>% relocate(assay, gene_name, uniprot_ID)

write.xlsx(tbl_out, paste0(out_dir, format(Sys.time(), "%Y-%m-%d_%H%M%S"), "_heva_results.xlsx"), asTable = T)
```


# Session information

```{r session information}
sessionInfo()
```
